name: ci
on: [push]
jobs:
  build-and-test:
    runs-on: ubuntu-24.04
    name: Build and test
    steps:
      - uses: actions/checkout@v4
      - uses: bahmutov/npm-install@v1
      - run: npm t

      - name: Example 1
        run: npm run example1
      - name: Example 2
        run: npm run example2
      - name: Example 3
        run: npm run example3
      - name: Example 4
        run: npm run example4
      - name: Demo README
        run: npm run demo-readme

      - name: AI example 1
        run: npm run ai-example1

      - name: Semantic Release 🚀
        # https://github.com/cycjimmy/semantic-release-action
        uses: cycjimmy/semantic-release-action@v4
        if: github.ref == 'refs/heads/main'
        with:
          branch: main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
