name: ci
on: [push]
jobs:
  build-and-test:
    runs-on: ubuntu-20.04
    name: Build and test
    steps:
      - uses: actions/checkout@v2
      - uses: bahmutov/npm-install@v1
      - run: npm t

      - name: Demo 1
        run: npm run demo
      - name: Demo 2
        run: npm run demo2

      - name: Semantic Release 🚀
        uses: cycjimmy/semantic-release-action@v2
        with:
          branch: main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
